# -*- coding: utf-8 -*-
"""Assignment 1_Parametric tests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gvAJE5Fsjdd16YglKP6uC3FJyLslcHmT

# Assignment 1_Parametric tests

BACKGROUND:
In a randomized control trial, 32 patients were divided into two groups: A and B. Group A received test drug whereas group B received placebo. The variable of interest was ‘Change in pain level’ measured by visual analogue scale (VAS)’ before treatment and after 3 days of treatment.
"""

# Import VAS DATA and name it as pain_vas. Check for normality of the data

library(readr)
library(dplyr)

pain_vas <- read_csv("/content/VAS DATA.csv")

# Check for normality
group_a <- pain_vas %>% filter(Group == 'A')
group_b <- pain_vas %>% filter(Group == 'B')

# Shapiro-Wilk test for normality
shapiro.test(group_a$VAS_before)
shapiro.test(group_a$VAS_after)
shapiro.test(group_b$VAS_before)
shapiro.test(group_b$VAS_after)

"""The results of the Shapiro-Wilk test for normality are:

Group A VAS_before:
p=0.528 (normal distribution)

Group A VAS_after:
p=0.034 (non-normal distribution)

Group B VAS_before:
p=0.979 (normal distribution)

Group B VAS_after:
p=0.805 (normal distribution)

"""

# Is post treatment VAS score significantly less as compared to ‘before treatment’ VAS score for Group A?

# Since Group A's post-treatment VAS score is non-normally distributed, we use the Wilcoxon Signed-Rank Test
wilcox.test(group_a$VAS_before, group_a$VAS_after, paired = TRUE)

"""p = 0.0004782 indicating a significant reduction in VAS score after treatment"""

#  Is Post Treatment VAS Score Significantly Less Compared to Pre-treatment for Group B?

# For Group B, both pre-treatment and post-treatment VAS scores are normally distributed, so we can use a Paired T-test.
t.test(group_b$VAS_before, group_b$VAS_after, paired = TRUE)

"""p = 0.02839 indicating a significant reduction in VAS score after treatment"""

# Is the Average Change in Pain Level for Group A Significantly More than Group B?

# Calculate the change in VAS
group_a$change_in_VAS <- group_a$VAS_before - group_a$VAS_after
group_b$change_in_VAS <- group_b$VAS_before - group_b$VAS_after

# Check normality using the Shapiro-Wilk test
shapiro_a_change <- shapiro.test(group_a$change_in_VAS)
shapiro_b_change <- shapiro.test(group_b$change_in_VAS)

shapiro_a_change
shapiro_b_change

"""The changes in VAS scores for both Group A and Group B follow a normal distribution."""

t_test_result <- t.test(group_a$change_in_VAS, group_b$change_in_VAS, var.equal = FALSE, alternative = "greater")
t_test_result

"""This suggests that the mean change in pain level for Group A is significantly greater than for Group B.

In other words, the treatment given to Group A is far more effective in reducing pain compared to the treatment received by Group B.
"""