# -*- coding: utf-8 -*-
"""Assignment 2_One way Anova.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PSz6qh7PcdkEu1t-kDebh_jkHX-hp2s

# Assignment 2_One way Anova


BACKGROUND:
A new marketing campaign was tested in 12 randomly selected stores of a large retail group. Usual campaign was run in another 12 randomly selected stores during the same month. The outcome variable is “Sales Growth”.


QUESTIONS-
Is the new campaign more effective than usual campaign?
In the campaign testing, store numbers 1-4 and 13-16 are from ‘West’, 5-8 and 17-20 are from ‘South’ and 9-12 and 21-24 are from ‘East’. Test the effect of ‘Zone’ in this business experiment.
"""

# Is the new campaign more effective than usual campaign?

library(ggplot2)
library(dplyr)

marketing_data <- read.csv("/content/M2 T2_anova assignment data.csv")

# check data
head(marketing_data)
summary(marketing_data)

# Summarize Growth by Campaign Type
aggregate(Growth ~ Campaign, data = marketing_data, summary)

# Visualize Growth by Campaign Type
ggplot(marketing_data, aes(x = Campaign, y = Growth, fill = Campaign)) +
  geom_boxplot() +
  labs(title = "Sales Growth by Campaign", y = "Sales Growth")

"""The sales growth under the new campaign appears to be higher overall compared to the usual campaign.

This suggests that the new campaign might be more effective than the usual campaign.
"""

# Summarize Growth by Zone
aggregate(Growth ~ Zone, data = marketing_data, summary)

# Visualize Growth by Zone
ggplot(marketing_data, aes(x = Zone, y = Growth, fill = Zone)) +
  geom_boxplot() +
  labs(title = "Sales Growth by Zone", y = "Sales Growth")

"""The West Zone has the highest median sales growth, followed by the East Zone, and finally the South Zone.

The West Zone also has the highest maximum growth value and a generally higher distribution of growth values.

These differences suggest that location may have an impact on sales growth
"""

# Check normality

shapiro.test(marketing_data$Growth[marketing_data$Campaign == "New"])
shapiro.test(marketing_data$Growth[marketing_data$Campaign == "Usual"])

"""Since the p-value is greater than 0.05 the sales growth data for the new campaign is normally distributed

Since the p-value is less than 0.05 the sales growth data for the usual campaign is not normally distributed

Since the new campaign data is normally distributed, but the usual campaign data is not, we should use a non-parametric test to compare the two campaigns effectively - The Mann-Whitney U test
"""

# Mann-Whitney U test
mann_whitney_result <- wilcox.test(Growth ~ Campaign, data = marketing_data, alternative = "greater")
print(mann_whitney_result)

# Tied values occur when two or more observations have the same value. In this case means that some stores had identical sales growth numbers.
table(marketing_data$Growth)

"""Three store have the same growth values 9.4 , 10.3 and 14.1. I ignore the as the sample size is reasonably large.

The p-value is significantly less than 0.05, we reject the null hypothesis.
This means that there is statistically significant evidence to conclude that the new marketing campaign results in greater sales growth compared to the usual campaign
"""

# Perform one-way ANOVA
anova_result <- aov(Growth ~ Zone, data = marketing_data)
summary(anova_result)

"""The p-value is significantly greater than 0.05, we fail to reject the null hypothesis.
This indicates that there is no statistically significant difference in sales growth among the three zones (West, South, East)
"""

# Tukey's HSD for post-hoc analysis
tukey_result <- TukeyHSD(anova_result)
print(tukey_result)

"""No need for it as one-way ANOVA test has shown that there is no statistically significant difference in sales growth among the three zones (West, South, East).

However, the Tukey test results indicate that there are no statistically significant differences in sales growth among the different zones (South, East, and West). This suggests that, based on the current data, location does not play a critical role in affecting sales growth in this marketing campaign.
"""

# Two-way ANOVA
two_way_anova <- aov(Growth ~ Campaign * Zone, data = marketing_data)
summary(two_way_anova)

"""Effect of Campaign: The campaign type has a significant effect on sales growth. This suggests that the new marketing campaign is effective in driving higher sales growth compared to the usual campaign.

Effect of Zone: There is no significant effect of the zone on sales growth. This indicates that sales growth does not vary significantly between the different zones.

Interaction Effect: There is no significant interaction effect between campaign type and zone. This suggests that the effect of the campaign on sales growth does not significantly differ by zone.

Conclusions: Implementing the new marketing campaign can enhance sales growth. The new campaign can be applied uniformly across all zones without the need for zone-specific adjustments.
"""