# -*- coding: utf-8 -*-
"""Assignment_1 Programming Basics - R.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LooSsBkiiAh8wCCxApDf-vWEoLhVHeA9

# Assignment_1 Programming Basics - R

## Create a matrix with three rows A, B and C and four columns with names Q, W, E and R. Fill the matrix with any numbers between 1 and 10.
"""

# Create a matrix with numbers between 1 and 10
mat <- matrix(sample(1:10, 12, replace = TRUE), nrow = 3)

# Assign names
rownames(mat) <- c("A", "B", "C")
colnames(mat) <- c("Q", "W", "E", "R")

print(mat)

"""## x = 24, y =”Hello World”, z = 93.65. Identify the class of x, y and z and convert all three into factor."""

x <- 24
y <- "Hello World"
z <- 93.65

# Print the classes
cat("Class of x:", class(x), "\n")
cat("Class of y:", class(y), "\n")
cat("Class of z:", class(z), "\n")

# Convert into factors
x <- as.factor(x)
y <- as.factor(y)
z <- as.factor(z)

# Print the classes
cat("Class of x:", class(x), "\n")
cat("Class of y:", class(y), "\n")
cat("Class of z:", class(z), "\n")

"""## q = 65.9836 a. Find square root of q and round it up to 3 digits. b. Check if log to the base 10 of q is less than 2."""

q <- 65.9836

sqrt_q <- round(sqrt(q), 3)

cat("Square root of q rounded to 3 decimal places:", sqrt_q, "\n")
cat("Is log10(q) less than 2?:", (log10(q) < 2), "\n")

"""## 4. x = c(“Intelligence”, “Knowledge”, “Wisdom”, “Comprehension”) y = “I am” z = “intelligent” a. Find first 4 letters of each word in x. b. Combine y and z to form a sentence “I am intelligent” c. Convert all the words in x to upper case."""

x <- c("Intelligence", "Knowledge", "Wisdom", "Comprehension")
y <- "I am"
z <- "intelligent"


first_4_letters <- substr(x, 1, 4)
cat(first_4_letters, "\n")


sentence <- paste(y, z)
cat(sentence, "\n")

x_upper <- toupper(x)
cat(x_upper, "\n")

"""## a = c(3,4,14,17,3,98,66,85,44) Print “Yes” if the numbers in ‘a’ are divisible by 3 and “No” if they are not divisible by 3 using ifelse()."""

a <- c(3, 4, 14, 17, 3, 98, 66, 85, 44)

result <- ifelse(a %% 3 == 0, "Yes", "No")

print (result)

"""## b = c(36,3,5,19,2,16,18,41,35,28,30,31) List all the numbers less than 30 in b using for loop."""

b <- c(36,3,5,19,2,16,18,41,35,28,30,31)
is_less_then_30 <- c()

for (item in b){
  if (item < 30)
    is_less_then_30 <- c(is_less_then_30,item)
}

print (is_less_then_30)

"""## Date = “01/30/18” a) Convert Date into standard date format (yyyy-mm-dd) and name it as Date_new. b) Extract day of week and month from Date_new. c) Find the difference in the current system date and Date_new."""

Date <- "01/30/18"

Date_new <- as.Date(Date, format = "%m/%d/%y")
Date_new

day_of_week <- weekdays(Date_new)
month <- months(Date_new)

print (day_of_week)
print (month)

current_date <- Sys.Date()
date_difference <- difftime(current_date, Date_new, units = "days")
date_difference