# -*- coding: utf-8 -*-
"""Assignment_3 Descriptive Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fXAmAwt5BnjaYZx9YL9cjNazetvGl0w
"""

# Import Premiums data.
Premium <- read.csv("/content/Premiums.csv")

# Obtain the Mode for the count of policies available across each Zone.

# Define a function to get the mode.
get_mode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

# Count policies by Zone and find the mode
policy_count <- table(Premium$ZONE_NAME)
mode <- get_mode(policy_count)
mode

# Obtain box-whisker plots for Vintage period.

boxplot(Premium$Vintage_Period, main="Boxplot of Vintage Period", ylab="Vintage Period")

# Detect outliers if present. Hint: use Boxplot() function of ‘car’ Package
install.packages("car")
library(car)

# Boxplot with outlier detection for Vintage period
Boxplot(Premium$Vintage_Period, main="Boxplot of Vintage Period with Outliers")

# Find skewness and kurtosis of Premium amount by Zone.

install.packages("e1071")
library(e1071)

f <- function(x)c(skew = skewness(x,type = 2),kurt = kurtosis(x,type = 2))
aggregate(Premium~ZONE_NAME,data = Premium,FUN = f)

# Alternative
skewness_by_zone <- tapply(Premium$Premium, Premium$ZONE_NAME, skewness)
kurtosis_by_zone <- tapply(Premium$Premium, Premium$ZONE_NAME, kurtosis)

print(skewness_by_zone)
print(kurtosis_by_zone)

# Draw a scatter plot of Premium and Vintage period.

plot(Premium$Premium, Premium$Vintage_Period,
     main="Scatter Plot of Premium vs Vintage Period",
     xlab="Premium Amount", ylab="Vintage Period", col="blue")

#Find the correlation coefficient between Premium and Vintage period and interpret the value.

correlation_coeff <- cor(Premium$Premium, Premium$Vintage_Period)
correlation_coeff

