# -*- coding: utf-8 -*-
"""Assignment_2 Data Management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hlSzvvDKBXE1cuwW76nspNUUQOJc-_6u
"""

# Import Premiums data and name it as Premium.
Premium <- read.csv("/content/Premiums.csv")

# Check number of rows, columns in the data.
cat( "Number of rows", nrow(Premium), "\n")
cat("Number of columns ", ncol(Premium))

# Display first 10 rows and last 5 rows.
head(Premium, 10)

tail(Premium,5)

# Describe (summarize) all variables.
summary(Premium)

# Display top 5 and bottom 5 policies in terms of premium amount.

Premium_Amount_Sorted <- Premium[sort(Premium$Premium_Amount, decreasing = TRUE)]

head(Premium_Amount_Sorted, 5)
tail(Premium_Amount_Sorted, 5)

# Calculate the sum for variable ‘Sum_Assured’ by ‘Region’ variable.
sum_assured_by_region <- aggregate(Sum_Assured ~ REGION, data = Premium, sum)
sum_assured_by_region

# Create a subset of policies of Asia Standard Plan with Sum_Assured < = 50,000.
# Keep variables Policy_No, Zone_name, Plan and Sum_Assured in the subset data.

subset_data <- subset(Premium, Plan == "Asia Standard Plan" & Sum_Assured <= 50000,
                      select = c(POLICY_NO, ZONE_NAME, Plan, Sum_Assured))
head(subset_data)

install.packages("openxlsx")

# Export the subsetted data into an xlsx file.

library(openxlsx)
write.xlsx(subset_data, "/content/Asia_Standard_Plan_Subset.xlsx")

